language: node_js
node_js:
  - "lts/*"

stages:
  - name: "Deploy gh-pages"
    if: branch = main AND NOT type = pull_request

jobs:
  include:
    - stage: "Deploy gh-pages"
      script: npm run build
      deploy:
        provider: pages
        local_dir: build
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: main
